Require Export Admissible.
Require Export Reduction.
Require Export Stdlib.Reals.Reals.
Require Export Embed.
Require Export PrimitiveSegment.
Require Export Segment.
Require Export SegmentsTranslation.
Require Export ListExt.
Require Export Stdlib.Logic.ClassicalDescription.
